name: Release Branch CI

on:
  push:
    branches:
      - release
jobs:
  build:
    name: Run Tests and Build Artifact
    runs-on: ubuntu-18.04
    env:
      ARTIFACT_NAME: "spring-boot-todolist"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run SonarQube Checks
        run: ./gradlew sonarqube

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/libs

  docker-publish:
    name: Build and Publish Docker Image
    needs: [ build ]
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/spring-boot-todolist
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: ./gradlew bootBuildImage

      - name: Publish Docker image
        run: docker push $DOCKER_IMAGE_NAME
